// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a 7-day social media content plan based on current trends and on-brand captions.
 *
 * - generateSevenDayContentPlan - A function that generates the content plan.
 * - SevenDayContentPlanInput - The input type for the generateSevenDayContentPlan function.
 * - SevenDayContentPlanOutput - The return type for the generateSevenDayContentPlan function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SevenDayContentPlanInputSchema = z.object({
  brandDescription: z.string().describe('Description of the brand, including its values, target audience, and key messaging.'),
  currentTrends: z.string().describe('Current trends in social media and the relevant industry.'),
});
export type SevenDayContentPlanInput = z.infer<typeof SevenDayContentPlanInputSchema>;

const SevenDayContentPlanOutputSchema = z.object({
  contentPlan: z.string().describe('A detailed 7-day social media content plan.'),
});
export type SevenDayContentPlanOutput = z.infer<typeof SevenDayContentPlanOutputSchema>;

export async function generateSevenDayContentPlan(input: SevenDayContentPlanInput): Promise<SevenDayContentPlanOutput> {
  return sevenDayContentPlanFlow(input);
}

const prompt = ai.definePrompt({
  name: 'sevenDayContentPlanPrompt',
  input: {schema: SevenDayContentPlanInputSchema},
  output: {schema: SevenDayContentPlanOutputSchema},
  prompt: `You are a social media expert. Generate a 7-day social media content plan based on the following information:

Brand Description: {{{brandDescription}}}

Current Trends: {{{currentTrends}}}

The content plan should include specific post ideas, caption suggestions, and optimal posting times.  Consider a variety of content types such as images, videos, stories, and live streams. Each day should have at least three content ideas.  Focus on creating engaging and on-brand content that aligns with current social media trends.
`,
});

const sevenDayContentPlanFlow = ai.defineFlow(
  {
    name: 'sevenDayContentPlanFlow',
    inputSchema: SevenDayContentPlanInputSchema,
    outputSchema: SevenDayContentPlanOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
